version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      time: "04:00"
      timezone: Europe/Berlin
    # to pip against the `develop` branch
    target-branch: "dev"
    # Labels on pull requests for version updates only
    labels:
      - "pip dependencies"
      
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 20
    versioning-strategy: increase